create schema "coords";
create schema "pdm";
create table "coords"."Axis" ("cyclic" boolean, "domainMax_value" float(53), "domainMin_value" float(53), "length" integer, "COORDSPACE_ID" bigint, "ID" bigint not null, "Axis_SUBTYPE" varchar(32) not null, "domainMax_unit" varchar(255), "domainMin_unit" varchar(255), "name" varchar(255), primary key ("ID"));
create table "coords"."CoordFrame" ("ID" bigint not null, "refDirection_ID" bigint unique, "refPosition_ID" bigint unique, "CoordFrame_SUBTYPE" varchar(32) not null, "equinox" varchar(255), "planetaryEphem" varchar(255), "spaceRefFrame" varchar(255), "timescale" varchar(255), primary key ("ID"));
create table "coords"."CoordSpace" ("ID" bigint not null, "CoordSpace_SUBTYPE" varchar(32) not null, "handedness" varchar(255) check ("handedness" in ('LEFT','RIGHT')), primary key ("ID"));
create table "coords"."CoordSys" ("ASTROCOORDSYSTEM_ID" bigint, "ID" bigint not null, "coordSpace_ID" bigint unique, "frame_ID" bigint unique, "pixelSpace_ID" bigint unique, "CoordSys_SUBTYPE" varchar(32) not null, primary key ("ID"));
create table "coords"."RefLocation" ("ID" bigint not null, "position_coordSys" bigint, "velocity_coordSys" bigint, "RefLocation_SUBTYPE" varchar(32) not null, "epoch" varchar(255), "position" varchar(255), primary key ("ID"));
create table "pdm"."AbstractProposal" ("ID" bigint not null, "scientificJustification_ID" bigint unique, "technicalJustification_ID" bigint unique, "AbstractProposal_SUBTYPE" varchar(64) not null, "kind" varchar(255) not null check ("kind" in ('STANDARD','TOO','SURVEY')), "summary" varchar(255) not null, "title" varchar(255) not null, primary key ("ID"));
create table "pdm"."AllocatedBlock" ("allocation_ORDER" integer, "ALLOCATEDPROPOSAL_ID" bigint, "ID" bigint not null, "grade" bigint not null, primary key ("ID"));
create table "pdm"."AllocatedProposal" ("ID" bigint not null, "PROPOSALCYCLE_ID" bigint, "submitted" bigint not null, primary key ("ID"));
create table "pdm"."AllocationGrade" ("ID" bigint not null, "PROPOSALCYCLE_ID" bigint, "description" varchar(255) not null, "name" varchar(255) not null, primary key ("ID"));
create table "pdm"."AvailableResources" ("ID" bigint not null, primary key ("ID"));
create table "pdm"."Backend" ("parallel" boolean not null, "ID" bigint not null, "OBSERVATORY_ID" bigint, "name" varchar(255) not null, primary key ("ID"));
create table "pdm"."CalibrationObservation" ("ID" bigint not null, "intent" varchar(255) not null check ("intent" in ('AMPLITUDE','ATMOSPHERIC','BANDPASS','PHASE','POINTING','FOCUS','POLARIZATION','DELAY')), primary key ("ID"));
create table "pdm"."CelestialTarget" ("parallax_value" float(53), "pmDec_value" float(53), "pmRA_value" float(53), "sourceCoordinates_lat_value" float(53) not null, "sourceCoordinates_lon_value" float(53) not null, "sourceVelocity_value" float(53), "ID" bigint not null, "sourceCoordinates_coordSys" bigint, "parallax_unit" varchar(255), "pmDec_unit" varchar(255), "pmRA_unit" varchar(255), "positionEpoch" varchar(255) not null, "sourceCoordinates_lat_unit" varchar(255) not null, "sourceCoordinates_lon_unit" varchar(255) not null, "sourceVelocity_unit" varchar(255), primary key ("ID"));
create table "pdm"."CommitteeMember" ("ID" bigint not null, "TAC_ID" bigint, "member" bigint not null, "role" varchar(255) not null check ("role" in ('TECHNICALREVIEWER','SCIENCEREVIEWER','CHAIR')), primary key ("ID"));
create table "pdm"."Ellipse" ("pAMajor_value" float(53) not null, "semiMajor_value" float(53) not null, "semiMinor_value" float(53) not null, "ID" bigint not null, "pAMajor_unit" varchar(255) not null, "semiMajor_unit" varchar(255) not null, "semiMinor_unit" varchar(255) not null, primary key ("ID"));
create table "pdm"."ExpectedSpectralLine" ("expectedSpectralLine_ORDER" integer, "restFrequency_value" float(53) not null, "ID" bigint not null, "SCIENCESPECTRALWINDOW_ID" bigint, "description" varchar(255) not null, "restFrequency_unit" varchar(255) not null, "splatalogId" varchar(255) not null, "transition" varchar(255), primary key ("ID"));
create table "pdm"."Field" ("ABSTRACTPROPOSAL_ID" bigint, "ID" bigint not null, "Field_SUBTYPE" varchar(64) not null, "name" varchar(255) not null, primary key ("ID"));
create table "pdm"."Filter" ("frequencyCoverage_end_value" float(53) not null, "frequencyCoverage_isSkyFrequency" boolean not null, "frequencyCoverage_spectralResolution_value" float(53) not null, "frequencyCoverage_start_value" float(53) not null, "ID" bigint not null, "description" varchar(255) not null, "frequencyCoverage_end_unit" varchar(255) not null, "frequencyCoverage_spectralResolution_unit" varchar(255) not null, "frequencyCoverage_start_unit" varchar(255) not null, "name" varchar(255) not null, "polarization" varchar(255) check ("polarization" in ('I','Q','U','V','RR','LL','RL','LR','XX','YY','XY','YX','PF','PP','PA')), primary key ("ID"));
create table "pdm"."Instrument" ("ID" bigint not null, "OBSERVATORY_ID" bigint, "description" varchar(255), "kind" varchar(255) not null check ("kind" in ('CONTINUUM','SPECTROSCOPIC')), "name" varchar(255) not null, "reference" varchar(255), "wikiId" varchar(255), primary key ("ID"));
create table "pdm"."Investigator" ("forPhD" boolean, "ABSTRACTPROPOSAL_ID" bigint, "ID" bigint not null, "person" bigint not null, "type" varchar(255) not null check ("type" in ('PI','COI')), primary key ("ID"));
create table "pdm"."Justification" ("ID" bigint not null, "text" varchar(4096) not null, "format" varchar(255) not null check ("format" in ('LATEX','RST','ASCIIDOC')), primary key ("ID"));
create table "pdm"."Observation" ("observations_ORDER" integer, "ABSTRACTPROPOSAL_ID" bigint, "ID" bigint not null, "field" bigint not null, "technicalGoal" bigint not null, "Observation_SUBTYPE" varchar(64) not null, primary key ("ID"));
create table "pdm"."ObservationConfiguration" ("ID" bigint not null, "SUBMITTEDPROPOSAL_ID" bigint, "mode" bigint not null, primary key ("ID"));
create table "pdm"."Observatory" ("ID" bigint not null, "homePage" varchar(255), primary key ("ID"));
create table "pdm"."ObservingConstraint" ("constraints_ORDER" integer, "ID" bigint not null, "OBSERVATION_ID" bigint, "ObservingConstraint_SUBTYPE" varchar(64) not null, primary key ("ID"));
create table "pdm"."ObservingMode" ("ID" bigint not null, "PROPOSALCYCLE_ID" bigint, "backend" bigint not null, "filter_ID" bigint unique, "instrument" bigint not null, "telescope" bigint not null, "description" varchar(255) not null, "name" varchar(255) not null, primary key ("ID"));
create table "pdm"."ObservingPlatform" ("ID" bigint not null, "ObservingPlatform_SUBTYPE" varchar(64) not null, primary key ("ID"));
create table "pdm"."ObservingProposal" ("ID" bigint not null, primary key ("ID"));
create table "pdm"."Organization" ("ID" bigint not null, "Organization_SUBTYPE" varchar(64) not null, "address" varchar(255) not null, "ivoid" varchar(255), "name" varchar(255) not null, "wikiId" varchar(255), primary key ("ID"));
create table "pdm"."PerformanceParameters" ("desiredAngularResolution_value" float(53), "desiredDynamicRange_value" float(53), "desiredLargestScale_value" float(53), "desiredSensitivity_value" float(53), "representativeSpectralPoint_value" float(53) not null, "ID" bigint not null, "desiredAngularResolution_unit" varchar(255), "desiredDynamicRange_unit" varchar(255), "desiredLargestScale_unit" varchar(255), "desiredSensitivity_unit" varchar(255), "representativeSpectralPoint_unit" varchar(255) not null, primary key ("ID"));
create table "pdm"."Person" ("ID" bigint not null, "homeInstitute" bigint not null, "eMail" varchar(255) not null, "fullName" varchar(255) not null, "orcidId" varchar(255), primary key ("ID"));
create table "pdm"."Point" ("ID" bigint not null, "centre_coordSys" bigint, primary key ("ID"));
create table "pdm"."PointingConstaint" ("ID" bigint not null, primary key ("ID"));
create table "pdm"."Polygon" ("ID" bigint not null, primary key ("ID"));
create table "pdm"."ProposalCycle" ("ID" bigint not null, "availableResources_ID" bigint unique, "observationSessionEnd" timestamp(6) not null, "observationSessionStart" timestamp(6) not null, "observatory" bigint not null, "submissionDeadline" timestamp(6), "tac_ID" bigint unique, "code" varchar(255), "instructions" varchar(255), "title" varchar(255) not null, primary key ("ID"));
create table "pdm"."ProposalReview" ("score" float(53) not null, "technicalFeasibility" boolean not null, "ID" bigint not null, "SUBMITTEDPROPOSAL_ID" bigint, "reviewDate" timestamp(6) not null, "reviewer" bigint not null, "comment" varchar(2048) not null, primary key ("ID"));
create table "pdm"."RelatedProposal" ("ABSTRACTPROPOSAL_ID" bigint, "ID" bigint not null, "proposal" bigint not null, primary key ("ID"));
create table "pdm"."Resource" ("amount" float(53) not null, "resources_ORDER" integer, "AVAILABLERESOURCES_ID" bigint, "ID" bigint not null, "type" bigint not null, primary key ("ID"));
create table "pdm"."ResourceBlock" ("ID" bigint not null, "mode" bigint not null, "resource_ID" bigint unique, "ResourceBlock_SUBTYPE" varchar(64) not null, primary key ("ID"));
create table "pdm"."ResourceType" ("ID" bigint not null, "name" varchar(255) not null, "unit" varchar(255) not null, primary key ("ID"));
create table "pdm"."Reviewer" ("ID" bigint not null, "person" bigint not null, primary key ("ID"));
create table "pdm"."ScienceSpectralWindow" ("spectralWindowSetup_end_value" float(53), "spectralWindowSetup_isSkyFrequency" boolean, "spectralWindowSetup_spectralResolution_value" float(53), "spectralWindowSetup_start_value" float(53), "spectrum_ORDER" integer, "ID" bigint not null, "TECHNICALGOAL_ID" bigint, "polarization" varchar(255) check ("polarization" in ('I','Q','U','V','RR','LL','RL','LR','XX','YY','XY','YX','PF','PP','PA')), "spectralWindowSetup_end_unit" varchar(255), "spectralWindowSetup_spectralResolution_unit" varchar(255), "spectralWindowSetup_start_unit" varchar(255), primary key ("ID"));
create table "pdm"."SimultaneityConstraint" ("ID" bigint not null, primary key ("ID"));
create table "pdm"."SolarSystemTarget" ("ID" bigint not null, primary key ("ID"));
create table "pdm"."SubmittedProposal" ("successful" boolean not null, "ID" bigint not null, "PROPOSALCYCLE_ID" bigint, "reviewsCompleteDate" timestamp(6) not null, "submissionDate" timestamp(6) not null, "proposalCode" varchar(255) not null, primary key ("ID"));
create table "pdm"."SupportingDocument" ("supportingDocuments_ORDER" integer, "ABSTRACTPROPOSAL_ID" bigint, "ID" bigint not null, "location" varchar(255) not null, "title" varchar(255) not null, primary key ("ID"));
create table "pdm"."TAC" ("ID" bigint not null, primary key ("ID"));
create table "pdm"."Target" ("ABSTRACTPROPOSAL_ID" bigint, "ID" bigint not null, "Target_SUBTYPE" varchar(64) not null, "sourceName" varchar(255) not null, primary key ("ID"));
create table "pdm"."TargetField" ("ID" bigint not null, primary key ("ID"));
create table "pdm"."TargetObservation" ("ID" bigint not null, primary key ("ID"));
create table "pdm"."TechnicalGoal" ("technicalGoals_ORDER" integer, "ABSTRACTPROPOSAL_ID" bigint, "ID" bigint not null, "performance_ID" bigint unique, primary key ("ID"));
create table "pdm"."Telescope" ("location_x_value" float(53) not null, "location_y_value" float(53) not null, "location_z_value" float(53) not null, "ID" bigint not null, "OBSERVATORY_ID" bigint, "location_coordSys" bigint, "location_x_unit" varchar(255) not null, "location_y_unit" varchar(255) not null, "location_z_unit" varchar(255) not null, "name" varchar(255) not null, "wikiId" varchar(255), primary key ("ID"));
create table "pdm"."TelescopeArray" ("ID" bigint not null, "OBSERVATORY_ID" bigint, "name" varchar(255) not null, primary key ("ID"));
create table "pdm"."TelescopeArrayMember" ("ID" bigint not null, "TELESCOPEARRAY_ID" bigint, "telescope" bigint not null, primary key ("ID"));
create table "pdm"."TimingConstraint" ("isAvoidConstraint" boolean, "ID" bigint not null, "note" varchar(255), primary key ("ID"));
create table "pdm"."TimingWindow" ("ID" bigint not null, "endTime" timestamp(6), "startTime" timestamp(6), primary key ("ID"));
create sequence "AbstractProposal_SEQ" start with 1 increment by 50;
create sequence "AllocatedProposal_SEQ" start with 1 increment by 50;
create sequence "AllocationGrade_SEQ" start with 1 increment by 50;
create sequence "AvailableResources_SEQ" start with 1 increment by 50;
create sequence "Axis_SEQ" start with 1 increment by 50;
create sequence "Backend_SEQ" start with 1 increment by 50;
create sequence "CommitteeMember_SEQ" start with 1 increment by 50;
create sequence "CoordFrame_SEQ" start with 1 increment by 50;
create sequence "CoordSpace_SEQ" start with 1 increment by 50;
create sequence "CoordSys_SEQ" start with 1 increment by 50;
create sequence "ExpectedSpectralLine_SEQ" start with 1 increment by 50;
create sequence "Field_SEQ" start with 1 increment by 50;
create sequence "Filter_SEQ" start with 1 increment by 50;
create sequence "Instrument_SEQ" start with 1 increment by 50;
create sequence "Investigator_SEQ" start with 1 increment by 50;
create sequence "Justification_SEQ" start with 1 increment by 50;
create sequence "ObservationConfiguration_SEQ" start with 1 increment by 50;
create sequence "Observation_SEQ" start with 1 increment by 50;
create sequence "ObservingConstraint_SEQ" start with 1 increment by 50;
create sequence "ObservingMode_SEQ" start with 1 increment by 50;
create sequence "ObservingPlatform_SEQ" start with 1 increment by 50;
create sequence "Organization_SEQ" start with 1 increment by 50;
create sequence "PerformanceParameters_SEQ" start with 1 increment by 50;
create sequence "Person_SEQ" start with 1 increment by 50;
create sequence "ProposalCycle_SEQ" start with 1 increment by 50;
create sequence "ProposalReview_SEQ" start with 1 increment by 50;
create sequence "RefLocation_SEQ" start with 1 increment by 50;
create sequence "RelatedProposal_SEQ" start with 1 increment by 50;
create sequence "ResourceBlock_SEQ" start with 1 increment by 50;
create sequence "ResourceType_SEQ" start with 1 increment by 50;
create sequence "Resource_SEQ" start with 1 increment by 50;
create sequence "Reviewer_SEQ" start with 1 increment by 50;
create sequence "ScienceSpectralWindow_SEQ" start with 1 increment by 50;
create sequence "SupportingDocument_SEQ" start with 1 increment by 50;
create sequence "TAC_SEQ" start with 1 increment by 50;
create sequence "Target_SEQ" start with 1 increment by 50;
create sequence "TechnicalGoal_SEQ" start with 1 increment by 50;
create sequence "TelescopeArrayMember_SEQ" start with 1 increment by 50;
create table "ObservationConfiguration_Observation" ("ObservationConfiguration_ID" bigint not null, "observation_ID" bigint not null);
create table "Observation_Target" ("Observation_ID" bigint not null, "target_ID" bigint not null);
create table "Polygon_points" ("points_lat_value" float(53), "points_lon_value" float(53), "containerId" bigint not null, "points_coordSys" bigint, "points_lat_unit" varchar(255), "points_lon_unit" varchar(255));
create table "SubjectMap" ("_id" bigint generated by default as identity, "person_id" bigint unique, "uid" varchar(255), primary key ("_id"));
alter table if exists "coords"."Axis" add constraint "FKbo11opyp1csmxjyly4uk0q4ul" foreign key ("COORDSPACE_ID") references "coords"."CoordSpace";
alter table if exists "coords"."CoordFrame" add constraint "FKpd6a5tktqqvn7qrmh1r9o6368" foreign key ("refDirection_ID") references "coords"."RefLocation";
alter table if exists "coords"."CoordFrame" add constraint "FK5g6eymwmagke7475lk25u0lj5" foreign key ("refPosition_ID") references "coords"."RefLocation";
alter table if exists "coords"."CoordSys" add constraint "FKs9dcgbc69g9w20fjxkkyc9i7g" foreign key ("pixelSpace_ID") references "coords"."CoordSpace";
alter table if exists "coords"."CoordSys" add constraint "FKcnb4ae4b0p3blmi3gd6y6cy3o" foreign key ("coordSpace_ID") references "coords"."CoordSpace";
alter table if exists "coords"."CoordSys" add constraint "FKfqnfwy8wdnv9ekex9e5ukq4wt" foreign key ("frame_ID") references "coords"."CoordFrame";
alter table if exists "coords"."CoordSys" add constraint "FKni0w4gitato7rhboph62tyqxk" foreign key ("ASTROCOORDSYSTEM_ID") references "coords"."CoordSys";
alter table if exists "coords"."RefLocation" add constraint "FK70rt29klb1v4otp21c4h1te1g" foreign key ("position_coordSys") references "coords"."CoordSys";
alter table if exists "coords"."RefLocation" add constraint "FKg0pwn54yk2d0p501kui11p9c0" foreign key ("velocity_coordSys") references "coords"."CoordSys";
alter table if exists "pdm"."AbstractProposal" add constraint "FKo753fqs3hddd9p8yeh4l17p6y" foreign key ("scientificJustification_ID") references "pdm"."Justification";
alter table if exists "pdm"."AbstractProposal" add constraint "FK78jal9lhl27iej0b7brrobf3o" foreign key ("technicalJustification_ID") references "pdm"."Justification";
alter table if exists "pdm"."AllocatedBlock" add constraint "FK95o2gu7ytej2mxcpg4f9ao1p2" foreign key ("grade") references "pdm"."AllocationGrade";
alter table if exists "pdm"."AllocatedBlock" add constraint "FKbh0ou3ys4f2y0wwwrraj9s4cn" foreign key ("ID") references "pdm"."ResourceBlock";
alter table if exists "pdm"."AllocatedBlock" add constraint "FKc40sye36w461gk4tt82ya9k7x" foreign key ("ALLOCATEDPROPOSAL_ID") references "pdm"."AllocatedProposal";
alter table if exists "pdm"."AllocatedProposal" add constraint "FK5of84tjeqef68lrk9fx6xauuj" foreign key ("submitted") references "pdm"."SubmittedProposal";
alter table if exists "pdm"."AllocatedProposal" add constraint "FKd792pmw47a58j2xkb5nv1k1lq" foreign key ("PROPOSALCYCLE_ID") references "pdm"."ProposalCycle";
alter table if exists "pdm"."AllocationGrade" add constraint "FKj1jkyonwwx7xeud42p7ik975w" foreign key ("PROPOSALCYCLE_ID") references "pdm"."ProposalCycle";
alter table if exists "pdm"."Backend" add constraint "FKjhf0er3xqvpb3640j0grlxjyf" foreign key ("OBSERVATORY_ID") references "pdm"."Observatory";
alter table if exists "pdm"."CalibrationObservation" add constraint "FKge5n690d5max1xhaph3rj920c" foreign key ("ID") references "pdm"."Observation";
alter table if exists "pdm"."CelestialTarget" add constraint "FKook4snv2p0ckumni4r6iwys1w" foreign key ("sourceCoordinates_coordSys") references "coords"."CoordSys";
alter table if exists "pdm"."CelestialTarget" add constraint "FK7rin0aebpa0vpw2rnd9xvo7qo" foreign key ("ID") references "pdm"."Target";
alter table if exists "pdm"."CommitteeMember" add constraint "FKi770s8i2riavg11jwrfao084b" foreign key ("member") references "pdm"."Reviewer";
alter table if exists "pdm"."CommitteeMember" add constraint "FK90j6hq8p4mfe744mimdfd3rmr" foreign key ("TAC_ID") references "pdm"."TAC";
alter table if exists "pdm"."Ellipse" add constraint "FK9ptf9hni6h956irj22uk97rcw" foreign key ("ID") references "pdm"."Field";
alter table if exists "pdm"."ExpectedSpectralLine" add constraint "FKg7y3t5r7v56r5fsw7j4mqhenh" foreign key ("SCIENCESPECTRALWINDOW_ID") references "pdm"."ScienceSpectralWindow";
alter table if exists "pdm"."Field" add constraint "FKbwnqbqdqe5mecvqa2elltpao5" foreign key ("ABSTRACTPROPOSAL_ID") references "pdm"."AbstractProposal";
alter table if exists "pdm"."Instrument" add constraint "FKr82ormqqjuhb9ymnov2d9dlee" foreign key ("OBSERVATORY_ID") references "pdm"."Observatory";
alter table if exists "pdm"."Investigator" add constraint "FK3jwb1nm21cpmsa9va4s6la570" foreign key ("person") references "pdm"."Person";
alter table if exists "pdm"."Investigator" add constraint "FKfmhmirxyh706j43a5174g49at" foreign key ("ABSTRACTPROPOSAL_ID") references "pdm"."AbstractProposal";
alter table if exists "pdm"."Observation" add constraint "FK9d518u6vyeunjetq93g3n8lgo" foreign key ("field") references "pdm"."Field";
alter table if exists "pdm"."Observation" add constraint "FKdotjn5m8njktgkmlpyh1u2bwv" foreign key ("technicalGoal") references "pdm"."TechnicalGoal";
alter table if exists "pdm"."Observation" add constraint "FK54rkr1oeuxfjr411bm243e95d" foreign key ("ABSTRACTPROPOSAL_ID") references "pdm"."AbstractProposal";
alter table if exists "pdm"."ObservationConfiguration" add constraint "FKqx17gnmtnm6lqiq7plhbk9ah" foreign key ("mode") references "pdm"."ObservingMode";
alter table if exists "pdm"."ObservationConfiguration" add constraint "FKgu3dcf1sxb5ui68tq9u9tb1dv" foreign key ("SUBMITTEDPROPOSAL_ID") references "pdm"."SubmittedProposal";
alter table if exists "pdm"."Observatory" add constraint "FK4dyky5x7p6tkansbhu7y45n3x" foreign key ("ID") references "pdm"."Organization";
alter table if exists "pdm"."ObservingConstraint" add constraint "FKkuq65qssxmyp6413ddgtgpgdj" foreign key ("OBSERVATION_ID") references "pdm"."Observation";
alter table if exists "pdm"."ObservingMode" add constraint "FKe4w39rgfkgdcf31xpf15icftm" foreign key ("backend") references "pdm"."Backend";
alter table if exists "pdm"."ObservingMode" add constraint "FKq7992fapno4l751wif2ojmowa" foreign key ("filter_ID") references "pdm"."Filter";
alter table if exists "pdm"."ObservingMode" add constraint "FKkm51ghhtf6vca9fc1mye3qio9" foreign key ("instrument") references "pdm"."Instrument";
alter table if exists "pdm"."ObservingMode" add constraint "FK7y4mapib6l5smcxiuup5y5j8o" foreign key ("telescope") references "pdm"."ObservingPlatform";
alter table if exists "pdm"."ObservingMode" add constraint "FKnt4tn2q4w250jd21aab4x107c" foreign key ("PROPOSALCYCLE_ID") references "pdm"."ProposalCycle";
alter table if exists "pdm"."ObservingProposal" add constraint "FKs72yi6y9y35ugneskjm88fylk" foreign key ("ID") references "pdm"."AbstractProposal";
alter table if exists "pdm"."Person" add constraint "FKbu2ysxtoodiciramxk7i1d7gi" foreign key ("homeInstitute") references "pdm"."Organization";
alter table if exists "pdm"."Point" add constraint "FKgof568xe81t9nccip9tbqw094" foreign key ("centre_coordSys") references "coords"."CoordSys";
alter table if exists "pdm"."Point" add constraint "FKmpdw28kyjhcncyy6g8g3cut6y" foreign key ("ID") references "pdm"."Field";
alter table if exists "pdm"."PointingConstaint" add constraint "FKdjlde6pl7smumfksvba81chv4" foreign key ("ID") references "pdm"."ObservingConstraint";
alter table if exists "pdm"."Polygon" add constraint "FKrr6n0319hmsl0oqne7hdvdwfk" foreign key ("ID") references "pdm"."Field";
alter table if exists "pdm"."ProposalCycle" add constraint "FK33jf654m8bdbymf2nhjdqteka" foreign key ("availableResources_ID") references "pdm"."AvailableResources";
alter table if exists "pdm"."ProposalCycle" add constraint "FKb2yha42s0kkulqnwmm23um3yd" foreign key ("observatory") references "pdm"."Observatory";
alter table if exists "pdm"."ProposalCycle" add constraint "FK3gw62aicy25lb499wmct1ide4" foreign key ("tac_ID") references "pdm"."TAC";
alter table if exists "pdm"."ProposalReview" add constraint "FK47wchhgmknle8gua1ne3nnrjr" foreign key ("reviewer") references "pdm"."Reviewer";
alter table if exists "pdm"."ProposalReview" add constraint "FK5jek0h7qmoxfv4k0diaxv7mhm" foreign key ("SUBMITTEDPROPOSAL_ID") references "pdm"."SubmittedProposal";
alter table if exists "pdm"."RelatedProposal" add constraint "FKbxg5o1ls733yjihhr135eoxsq" foreign key ("proposal") references "pdm"."AbstractProposal";
alter table if exists "pdm"."RelatedProposal" add constraint "FK9h38bvp97sb3ibjw042texq5h" foreign key ("ABSTRACTPROPOSAL_ID") references "pdm"."AbstractProposal";
alter table if exists "pdm"."Resource" add constraint "FKk0uvh5p6cr8van4fk9haw3oc7" foreign key ("type") references "pdm"."ResourceType";
alter table if exists "pdm"."Resource" add constraint "FKdx99cx9vol2mat6rcbsc6e8rt" foreign key ("AVAILABLERESOURCES_ID") references "pdm"."AvailableResources";
alter table if exists "pdm"."ResourceBlock" add constraint "FKivjwb61pnx063q342ahvdgr5n" foreign key ("mode") references "pdm"."ObservingMode";
alter table if exists "pdm"."ResourceBlock" add constraint "FKq1jwnb129v7yetwk5baucwr54" foreign key ("resource_ID") references "pdm"."Resource";
alter table if exists "pdm"."Reviewer" add constraint "FKrbiie2ioba5222a2mxl250xv4" foreign key ("person") references "pdm"."Person";
alter table if exists "pdm"."ScienceSpectralWindow" add constraint "FKmx2sm679926huiy3mpw7nedea" foreign key ("TECHNICALGOAL_ID") references "pdm"."TechnicalGoal";
alter table if exists "pdm"."SimultaneityConstraint" add constraint "FKh9e5wxe3fh1w6665575df9y75" foreign key ("ID") references "pdm"."TimingConstraint";
alter table if exists "pdm"."SolarSystemTarget" add constraint "FK43fej7bak44ffg5td2gik81w5" foreign key ("ID") references "pdm"."Target";
alter table if exists "pdm"."SubmittedProposal" add constraint "FKklhr712diwu6wnrhy1r5swgw0" foreign key ("ID") references "pdm"."AbstractProposal";
alter table if exists "pdm"."SubmittedProposal" add constraint "FK78guh9bgirgxh6bhw50v8c7d" foreign key ("PROPOSALCYCLE_ID") references "pdm"."ProposalCycle";
alter table if exists "pdm"."SupportingDocument" add constraint "FKli4h36kt4kcx468ppflrrxbpw" foreign key ("ABSTRACTPROPOSAL_ID") references "pdm"."AbstractProposal";
alter table if exists "pdm"."Target" add constraint "FKt6wd1513bcurjgopx4jbyeirn" foreign key ("ABSTRACTPROPOSAL_ID") references "pdm"."AbstractProposal";
alter table if exists "pdm"."TargetField" add constraint "FKd9ewwrkocwhs84c1223yem44u" foreign key ("ID") references "pdm"."Field";
alter table if exists "pdm"."TargetObservation" add constraint "FKpiwgw3vy54wqelr98rb9we53t" foreign key ("ID") references "pdm"."Observation";
alter table if exists "pdm"."TechnicalGoal" add constraint "FK6f45xnvlg0uhsqoh1hry3t018" foreign key ("performance_ID") references "pdm"."PerformanceParameters";
alter table if exists "pdm"."TechnicalGoal" add constraint "FKbixfcj8c0h41hn7hjk5o3vhry" foreign key ("ABSTRACTPROPOSAL_ID") references "pdm"."AbstractProposal";
alter table if exists "pdm"."Telescope" add constraint "FK90397g8ru0u9e2g802re7ot7o" foreign key ("location_coordSys") references "coords"."CoordSys";
alter table if exists "pdm"."Telescope" add constraint "FK5ct4onam3xqh3eqxifrsq4x78" foreign key ("ID") references "pdm"."ObservingPlatform";
alter table if exists "pdm"."Telescope" add constraint "FKgha7oxkud1hs3tq81mhgld3hd" foreign key ("OBSERVATORY_ID") references "pdm"."Observatory";
alter table if exists "pdm"."TelescopeArray" add constraint "FK1e1rgtssp0o3co8euellpuqj9" foreign key ("ID") references "pdm"."ObservingPlatform";
alter table if exists "pdm"."TelescopeArray" add constraint "FKsricyi5n7pxgpr12kljrtl0q5" foreign key ("OBSERVATORY_ID") references "pdm"."Observatory";
alter table if exists "pdm"."TelescopeArrayMember" add constraint "FK89lglrpdl29qcor5ad1lnv8ws" foreign key ("telescope") references "pdm"."Telescope";
alter table if exists "pdm"."TelescopeArrayMember" add constraint "FKlf5xmcxw7akjuxoh5m9ll0oj0" foreign key ("TELESCOPEARRAY_ID") references "pdm"."TelescopeArray";
alter table if exists "pdm"."TimingConstraint" add constraint "FKdcqxqlk2y4ib9cgho367pfv3s" foreign key ("ID") references "pdm"."ObservingConstraint";
alter table if exists "pdm"."TimingWindow" add constraint "FKm4j9qru31oug27sm4icwc6y4x" foreign key ("ID") references "pdm"."TimingConstraint";
alter table if exists "ObservationConfiguration_Observation" add constraint "FK5fxi7y2r3ogeqese6v3cijpmb" foreign key ("observation_ID") references "pdm"."Observation";
alter table if exists "ObservationConfiguration_Observation" add constraint "FKovbvgsbg9sv7it2167l2r19v0" foreign key ("ObservationConfiguration_ID") references "pdm"."ObservationConfiguration";
alter table if exists "Observation_Target" add constraint "FKee9rjrgbg159d20vbyc0duc9m" foreign key ("target_ID") references "pdm"."Target";
alter table if exists "Observation_Target" add constraint "FKqjr3ry7uig2bi8h6wk4bfofpm" foreign key ("Observation_ID") references "pdm"."Observation";
alter table if exists "Polygon_points" add constraint "FKdkoq07m8d17sgo87oe83l7x5v" foreign key ("points_coordSys") references "coords"."CoordSys";
alter table if exists "Polygon_points" add constraint "FK5raw1i6j46rxgupoc6dxrf2u1" foreign key ("containerId") references "pdm"."Polygon";
alter table if exists "SubjectMap" add constraint "FKtogn9po7gau8ne7wd82v3agqh" foreign key ("person_id") references "pdm"."Person";
